apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx-demo
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: APP_MODE
            - name: IMPORTANT_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: IMPORTANT_CONFIG
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: top-secret
                  key: DB_PASSWORD


